### ISSUE TITLE
Add the github icon in svg or png form in the Top right corner of header in jarvis web

### ISSUE THREAD

**Issue by TeAmP0is0N** [the-vision/jarvis-web#10]
When a user will click on this icon then it should show a pop-up type that will point the address of our GitHub Repo .

**Comment by abhu-A-J** [comment]
@TeAmP0is0N I'll like to do this.

**Comment by TeAmP0is0N** [comment]
@abhu-A-J I have assigned this issue to you. Let me know if you need any help.
