### ISSUE TITLE
In projects menu add the details about our all products of Jarvis

### ISSUE THREAD

**Issue by TeAmP0is0N** [the-vision/jarvis-web#15]
ie: 1. Jarvis Telegram  2. Jarvis Core   3. Jarvis Slack  4. Jarvis Discord  
These products should be in a column and also add some description of these products. 
https://github.com/the-vision

**Comment by divyaprakash-Rx** [comment]
@TeamP0is0N I want to work pn this issue.
Please assign it to me.

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx I have assigned this issue to you. Let me know if you need any help.

**Comment by divyaprakash-Rx** [comment]
Ok

**Comment by divyaprakash-Rx** [comment]
@TeAmP0is0N Where I have to write the details.
In about.vue or I have to create new file?

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx You have to show this information in projects. You can create a new file as well.

**Comment by divyaprakash-Rx** [comment]
Ok

**Comment by divyaprakash-Rx** [comment]
@TeAmP0is0N Please check the details and provide suggestion if any improvement is needed.
After that, I will add these to details page.
[jarvis details.docx](https://github.com/the-vision/jarvis-web/files/4364913/jarvis.details.docx)

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx It is fine.

**Comment by divyaprakash-Rx** [comment]
@TeAmP0is0N I have created the PR after adding the same details. Please look into that and merge the PR.
