### ISSUE TITLE
Needs to improve the header section.

### ISSUE THREAD

**Issue by sgpritam** [the-vision/jarvis-web#17]
There is a need to improve the header part as you can enhance the design and add some attractive features.
![image](https://user-images.githubusercontent.com/41269164/77117105-56d94500-6a57-11ea-8db0-e766a5240be3.png)

**Comment by abhu-A-J** [comment]
@sgpritam Sir this was attended when the navigation bar was built via #16

**Comment by sgpritam** [comment]
@abhu-A-J There is a need to develop more things like logo and UI

**Comment by abhu-A-J** [comment]
> @abhu-A-J There is a need to develop more things like logo and UI

Can you explain in more detail about UI for it?? The logo is not an issue since we just need to replace the header (text) with the logo . Currently, the UI of navbar gave it as a hamburger option for mobile
