### ISSUE TITLE
Addition on footer

### ISSUE THREAD

**Issue by abhu-A-J** [the-vision/jarvis-web#18]
@tanisha03 there isn't any footer on the project as of now, so I would to introduce one to resonate with the new navigation built. If it's valid may I know the information you want on the footer??

**Comment by tanisha03** [comment]
@abhu-A-J I am open for suggestion, what all do you think will be useful?

**Comment by abhu-A-J** [comment]
@tanisha03  here a short info:
I think it should include some important links to other Jarvis projects like discord, telegram and more. 
A form for the newsletter, if there is one present (just the fronted work), copyright info, link to license pages, socials(if present) and also link to contributors page ??

**Comment by tanisha03** [comment]
@abhu-A-J I am not sure about the newsletter part, @swapagarwal can tell about it more. For now remove, the newsletter part and span out the other options and make a PR.

**Comment by abhu-A-J** [comment]
> @abhu-A-J I am not sure about the newsletter part, @swapagarwal can tell about it more. For now remove, the newsletter part and span out the other options and make a PR.

Could you elaborate on what you mean by spanning out other options? 
Should they go as row's rather than columns??

**Comment by tanisha03** [comment]
@abhu-A-J I mean remove the newsletter option for now and align the other two columns with proper spacing.
