### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by abhu-A-J** [the-vision/jarvis-web#26]
Add appropriate actions to do the following tasks:
- Give a message when creating an issue.
- Give a message when creating a PR to project.
- Actions to detect stale issues and PR and give labels to them. 
- Auto Assign reviewers to PR created.
- Detect any foul language/behavior.

@TeAmP0is0N Sir @tanisha03  Ma'am Do you think it's a good idea to add these to the repo??

**Comment by TeAmP0is0N** [comment]
Already we have these features. We can't Auto Assign reviewers. What do you say @tanisha03 and @swapagarwal ?

**Comment by abhu-A-J** [comment]
> Already we have these features. We can't Auto Assign reviewers. What do you say @tanisha03 and @swapagarwal ?

Sir, I don't think we have these features on this repo? Because I don't see any greetings on issues and PR and any actions present on the repo at the moment.?

**Comment by abhu-A-J** [comment]
> > Already we have these features. We can't Auto Assign reviewers. What do you say @tanisha03 and @swapagarwal ?
> 
> @TeAmP0is0N Sir, I don't think we have these features on this repo? Because I don't see any greetings on issues and PR and any actions present on the repo at the moment.?

**Comment by TeAmP0is0N** [comment]
@abhu-A-J Right. Remove these two features:
- Actions to detect stale issues and PR and give labels to them.
- Auto Assign reviewers to PR created.

**Comment by TeAmP0is0N** [comment]
@abhu-A-J Go ahead!
