### ISSUE TITLE
Add Material Icons

### ISSUE THREAD

**Issue by tanisha03** [the-vision/jarvis-web#28]
![Screenshot from 2020-04-06 15-00-09](https://user-images.githubusercontent.com/37444245/78544206-69090080-7817-11ea-8326-ffe7faa0f4c9.png)

Add appropriate material icon for Search bar and Send button.
Attach screenshots for reference.

**Comment by abhu-A-J** [comment]
@tanisha03 Ma'am Can I take this?

**Comment by tanisha03** [comment]
@abhu-A-J go ahead
