### ISSUE TITLE
Projects page

### ISSUE THREAD

**Issue by tanisha03** [the-vision/jarvis-web#29]
Make the layout for the Projects page to list out all the jarvis projects. Display the projects in card formant with description.
Add screenshots for reference.

**Comment by abhu-A-J** [comment]
> Make the layout for the Projects page to list out all the jarvis projects. Display the projects in card formant with description.
> Add screenshots for reference.

May I do this as well??Thank you

**Comment by tanisha03** [comment]
@abhu-A-J Complete the previous one please, I will assign you after that

**Comment by nandanasreeraj123** [comment]
I am having basic knowledge in UI-UX and front end....Can I take this up?

**Comment by abhu-A-J** [comment]
> @abhu-A-J Complete the previous one please, I will assign you after that

May I move forward Ma'am! I did the previous one ! Thank you!

**Comment by tanisha03** [comment]
@nandanasreeraj123 , I'm assigning this to @abhu-A-J since he commented first, look for some other issues to work on :) . I'll open a few as well in this repo. Keep an eye
