### ISSUE TITLE
Add details about Jarvis in the "About" section

### ISSUE THREAD

**Issue by tanisha03** [the-vision/jarvis-web#3]
For reference: https://chatwithjarvis.com/
When you make a pull request, make sure to attach a screenshot of the changes made.

**Comment by abhu-A-J** [comment]
@tanisha03 I know a little about react. Can I take this issue under GSSoC?? Thanks.!

**Comment by tanisha03** [comment]
@abhu-A-J you can refer a new tutorials online and I think you'll be good to go. For now, I'm assigning it to you, give it a try.

**Comment by abhu-A-J** [comment]
> @abhu-A-J you can refer a new tutorials online and I think you'll be good to go. For now, I'm assigning it to you, give it a try.

Yes,sure. I'll do that. Is there a time limit for the PR? (max days)

**Comment by tanisha03** [comment]
@abhu-A-J try to finish it within 3-4 days
