### ISSUE TITLE
404 Page for the project

### ISSUE THREAD

**Issue by abhu-A-J** [the-vision/jarvis-web#33]
Make a customizable page for 404 Error / unknown routes.

- Whenever a user enters a route / internal component redirect to the route which  does not exist apart from home, projects, about  page it tells the user a following information (IMG is shown below)  designed with illustration and enhanced with animations!
- It will let users go back to home page with a link given

![Screenshot (120)](https://user-images.githubusercontent.com/49617450/79046931-41f46980-7c31-11ea-8ccf-a55b4e54ca89.png)

@tanisha03 Ma'am @TeAmP0is0N Sir, I can make make this for the project? The above image is what I have planned!

**Comment by tanisha03** [comment]
@abhu-A-J go aheaad
