### ISSUE TITLE
Create a template for the "Chat" section.

### ISSUE THREAD

**Issue by tanisha03** [the-vision/jarvis-web#4]
Create a UI for the chat section.
Refer to https://dribbble.com/search/chat%20template%20desktop
Add in the screenshot of the changes made along with the pull requests.

**Comment by divyaprakash-Rx** [comment]
I want to work on this. Please assign it to me.

**Comment by tanisha03** [comment]
@divyaprakash-Rx you can work on it, let me know if there are some doubts.

**Comment by divyaprakash-Rx** [comment]
Ok

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx Are you working on it?

**Comment by divyaprakash-Rx** [comment]
Yes, it is almost done.

**Comment by divyaprakash-Rx** [comment]
@TeAmP0is0N please check my pull request.

**Comment by divyaprakash-Rx** [comment]
@TeamP0is0N please check my pull request chat section template is complete as suggested
