### ISSUE TITLE
Make the navbar responsive

### ISSUE THREAD

**Issue by tanisha03** [the-vision/jarvis-web#7]
Include the navbar options in the hamburger form for smaller screens. 
For reference: https://dribbble.com/search/hamburger%20navigation
Add in screenshots of your final UI.

**Comment by Ankita1811** [comment]
@tanisha03 Can I please work on this issue?

**Comment by sgpritam** [comment]
@Ankita1811 you can work on it now !!

**Comment by TeAmP0is0N** [comment]
@Ankita1811 Are you working on it?

**Comment by Ankita1811** [comment]
@TeAmP0is0N I am unable to complete this issue.

**Comment by TeAmP0is0N** [comment]
This issue is open for other persons.

**Comment by abhu-A-J** [comment]
@TeAmP0is0N can I take this issue??

**Comment by tanisha03** [comment]
@abhu-A-J go ahead
